kind: pipeline
type: docker
name: CI_CONSECO

trigger :
    event:
        - push

steps:
    - name: build
      image: mcr.microsoft.com/dotnet/sdk:6.0
      commands:
        - cd Code
        - dotnet restore CI_CONSECO.sln
        - dotnet build CI_CONSECO.sln -c Release --no-restore
        - dotnet publish CI_CONSECO.sln -c Release --no-restore -o CI_PROJECT_DIR/build/release
    - name: tests
      image: mcr.microsoft.com/dotnet/sdk:6.0
      commands:
        - cd Code
        - dotnet restore CI_CONSECO.sln
        - dotnet test CI_CONSECO.sln --no-restore
      depends_on: [build]
 #   - name: docker-build
 #     image: plugins/docker
 #     settings:
 #       dockerfile: Dockerfile
 #       context: .
 #       registry: hub.codefirst.iut.uca.fr
 #       repo: hub.codefirst.iut.uca.fr/hugo.livet/ConsEco
 #       username:
 #         from_secret: SonarConsEco
 #       password:
 #         from_secret: sqp_ffc02968e133d03daeb917e8c2e6f243a80d087a